version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "23:30"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: deck.gl
    versions:
    - 8.3.12
    - 8.4.0
  - dependency-name: eslint
    versions:
    - 7.16.0
    - 7.19.0
  - dependency-name: rc-slider
    versions:
    - 9.7.1
  - dependency-name: lint-staged
    versions:
    - 10.5.3
  - dependency-name: react-scripts
    versions:
    - 4.0.1
  - dependency-name: bulma
    versions:
    - 0.9.1
  - dependency-name: react-image
    versions:
    - 3.0.3
